// plugins/output-angular/index.js
import { toAngular } from "./print.js";
import { identifier, templateText } from "../dsp-ir/emit.js";

const pascal = (sel) => identifier(String(sel).split(/[-_\s]/).filter(Boolean).map((p) => p[0].toUpperCase() + p.slice(1)).join(""), "Screen");

/**
 * Modern Angular as a target, which closes a loop: an AngularJS controller
 * from 2013 comes out the far end as a standalone component saying @for,
 * having passed through a middle that knows neither of them.
 *
 * Standalone, signal inputs, block control flow. The five year old dialect
 * this tool reads is not the Angular it writes, and that gap is the point.
 *
 *   angular: true
 */
export default {
  name: "output-angular",
  version: "0.1.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      if (!ctx.config.angular) return log.debug("not requested");

      let emitted = 0;
      for (const screen of ctx.screens) {
        const name = pascal(screen.selector);
        const result = screen.template ? toAngular(screen.template) : null;
        const collection = result?.collections[0] ?? "data";
        const inputs = [...new Set([...screen.inputs, ...(result?.reads ?? []), "loading", "error"])];
        await ctx.write(`src/app/${screen.selector}/${screen.selector}.component.ts`, COMPONENT({ name, selector: screen.selector, inputs, outputs: screen.outputs, result, collection, screen }));
        emitted += 1;
      }
      log.info(`${emitted} standalone component(s), block syntax`);
    });
  },
};

const COMPONENT = ({ name, selector, inputs, outputs, result, collection, screen }) => {
  const models = result?.models ?? [];
  const empty = collection === "data" ? "!this.data || (Array.isArray(this.data) && this.data.length === 0)" : `!this.${collection} || this.${collection}.length === 0`;

  return `import { Component, EventEmitter, Input, Output } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";

/**
 * Ported from ${screen.file} by portamp.
 *
 * Every state below is present on purpose. Delete one only when you have
 * checked the legacy screen genuinely cannot reach it.
 */
@Component({
  selector: "${selector}",
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: \`
    @if (loading) {
      <p class="state state--loading">Loading…</p>
    } @else if (error) {
      <div class="state state--error">
        <strong>Could not load</strong>
        <p>{{ errorText }}</p>
        <button type="button" (click)="retry.emit()">Try again</button>
      </div>
    } @else if (empty) {
      <p class="state state--empty">Nothing to show yet.</p>
    } @else {
${result ? templateText(result.markup) : "      <!-- No template was found for this component. -->"}
    }
  \`,
})
export class ${name}Component {
${inputs.map((i) => `  @Input() ${i}: any;`).join("\n")}
${outputs.map((o) => `  @Output() ${o} = new EventEmitter<any>();`).join("\n")}
  @Output() retry = new EventEmitter<void>();
${models.map((m) => `  ${m.split(".").pop().replace(/[^\w$]/g, "")} = "";`).join("\n")}

  get errorText() { return this.error ? String(this.error.message ?? this.error) : ""; }
  get empty() { return ${empty}; }
}
`;
};

// plugins/output-react/index.js
import { translate } from "./template.js";

const pascal = (sel) =>
  sel.split(/[-_]/).filter(Boolean).map((p) => p[0].toUpperCase() + p.slice(1)).join("");

const unique = (list) => [...new Set(list.filter(Boolean))];

/**
 * Emits one React component per Angular component. The template is translated
 * where there is one to translate, and every state is present either way: an
 * empty state that renders nothing is the single most common thing a port
 * forgets, and it is invisible in review because the screen looks fine when
 * the data happens to be there.
 */
export default {
  name: "output-react",
  version: "0.2.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      let translated = 0;

      for (const s of ctx.screens) {
        const Name = pascal(s.selector) || "Screen";
        const notes = [];
        if (s.usesTwoWay) notes.push(" * Two way binding in the original. Every input here is controlled.");
        if (s.rxjs.length)
          notes.push(` * RxJS in the original: ${s.rxjs.join(", ")}. Mapped to hooks, not ported one for one.`);

        let body = null;
        let models = [];
        let props = unique([...s.inputs, ...s.outputs.map((o) => `on${pascal(o)}`)]);
        let collection = "data";

        if (s.template) {
          const result = translate(s.template, { indent: 3 });
          body = result.jsx;
          models = result.models;
          collection = result.collections[0] ?? "data";
          props = unique([...props, ...result.reads]);
          translated += 1;
          notes.push(` * Template translated from ${s.templateOrigin ?? "the decorator"}.`);
          for (const note of result.notes) ctx.unverified(`<${s.selector}>: ${note}`);
        } else {
          notes.push(" * No template was found, so the body below is a placeholder.");
        }

        props = unique([...props, "loading", "error", "onRetry"]);
        const usesChildren = Boolean(body && body.includes("{children}"));
        if (usesChildren) props.push("children");

        await ctx.write(
          `src/features/${Name}/${Name}.jsx`,
          COMPONENT({ Name, props, notes, origin: s.file, body, models, collection })
        );
      }

      log.info(
        `${ctx.screens.length} component(s) emitted` +
          (ctx.screens.length ? `, ${translated} template(s) translated` : "")
      );
    });
  },
};

const PLACEHOLDER = (origin) =>
  `      {/* No template was found for this component. Port the body from ${origin}. */}`;

const COMPONENT = ({ Name, props, notes, origin, body, models, collection }) => {
  const state = models
    .map((m) => {
      const leaf = m.split(".").pop().replace(/[^\w$]/g, "");
      return `  const [${leaf}, set${leaf.charAt(0).toUpperCase()}${leaf.slice(1)}] = useState("");`;
    })
    .join("\n");

  const empty =
    collection === "data"
      ? "!data || (Array.isArray(data) && data.length === 0)"
      : `!${collection} || ${collection}.length === 0`;

  return `import React${models.length ? ", { useState }" : ""} from "react";
import { tokens as T } from "../../tokens.js";

/**
 * Ported from ${origin}
${notes.length ? notes.join("\n") : " *"}
 *
 * Every state below is present on purpose. Delete one only when you have
 * checked the legacy screen genuinely cannot reach it.
 */
export default function ${Name}({ ${props.join(", ")} }) {
${state ? state + "\n" : ""}  if (loading) return <div style={{ padding: T.space[4], color: T.color.inkMuted }}>Loading…</div>;

  if (error)
    return (
      <div style={{ padding: T.space[4] }}>
        <div style={{ fontWeight: T.weight.bold, marginBottom: T.space[0] }}>Could not load</div>
        <div style={{ color: T.color.inkMuted, fontSize: T.size.sm }}>{String(error.message ?? error)}</div>
        <button onClick={onRetry} style={{ marginTop: T.space[2] }}>Try again</button>
      </div>
    );

  if (${empty})
    return (
      <div style={{ padding: T.space[5], textAlign: "center", color: T.color.inkMuted }}>
        Nothing to show yet.
      </div>
    );

  return (
    <div style={{ padding: T.space[3], color: T.color.ink, background: T.color.surface }}>
${body ?? PLACEHOLDER(origin)}
    </div>
  );
}
`;
};
