// plugins/output-solid/index.js
import { buildIr } from "../dsp-ir/ir.js";
import { jsString } from "../dsp-ir/emit.js";

/**
 * The Solid target. Solid is the one target where spelling matters for
 * correctness, not taste: a destructured prop stops updating and a signal
 * read without its call never updates at all. So this printer rewrites every
 * expression, qualifying props as props.x and signals as x(), instead of
 * emitting code that looks right and quietly is not reactive.
 */

const pascal = (sel) =>
  String(sel).split(/[-_\s]/).filter(Boolean).map((p) => p[0].toUpperCase() + p.slice(1)).join("");

const unique = (list) => [...new Set(list)];
const pad = (depth) => "  ".repeat(depth);
const camel = (s) => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

/** Rewrite bare root identifiers by the map, leaving strings and keys alone. */
export function qualify(code, rewrite, locals = new Set()) {
  const text = String(code);
  const strings = [];
  // The placeholder cannot collide with code: NUL never appears in a template
  // expression, and a bare number would.
  const masked = text.replace(/'(?:\\.|[^'\\])*'|"(?:\\.|[^"\\])*"|`(?:\\.|[^`\\])*`/g, (s) => {
    strings.push(s);
    return `\u0000${strings.length - 1}\u0000`;
  });
  const rewritten = masked.replace(/(\.\s*)?\b([A-Za-z_$][\w$]*)\b(\s*:)?/g, (m, dot, name, colon) => {
    if (dot || colon || locals.has(name) || !rewrite.has(name)) return m;
    return rewrite.get(name);
  });
  return rewritten.replace(/\u0000(\d+)\u0000/g, (_, i) => strings[Number(i)]);
}

function attributes(node, ctx) {
  const out = [];
  const q = (code) => qualify(code, ctx.rewrite, ctx.locals);

  const literal = node.classes.filter((c) => c.kind === "literal").map((c) => c.value).join(" ").trim();
  const dynamic = node.classes.filter((c) => c.kind !== "literal");
  if (literal && !dynamic.length) out.push(`class=${jsString(literal)}`);
  else if (dynamic.length) {
    const parts = [
      ...(literal ? [jsString(literal)] : []),
      ...dynamic.map((c) => (c.kind === "conditional" ? `${q(c.when)} && ${jsString(c.name)}` : q(c.expression))),
    ];
    out.push(`class={[${parts.join(", ")}].filter(Boolean).join(" ")}`);
  }

  for (const attr of node.attrs) {
    if (attr.kind === "flag") out.push(attr.name);
    else if (attr.kind === "static") out.push(`${attr.name}=${jsString(attr.value)}`);
    else if (attr.kind === "bound") out.push(`${attr.name}={${q(attr.expression)}}`);
    else if (attr.kind === "template") {
      out.push(`${attr.name}={\`${attr.parts.map((p) => (p.expression !== undefined ? `\${${q(p.expression)}}` : p.literal)).join("")}\`}`);
    }
  }

  if (node.model) {
    const leaf = node.model.split(".").pop().replace(/[^\w$]/g, "");
    const setter = `set${leaf.charAt(0).toUpperCase()}${leaf.slice(1)}`;
    if (node.modelKind === "checkbox") {
      out.push(`checked={${leaf}()}`, `onChange={(e) => ${setter}(e.target.checked)}`);
    } else if (node.modelKind === "radio") {
      const own = node.attrs.find((a) => a.name.toLowerCase() === "value");
      const option = own?.kind === "static" ? jsString(own.value) : own?.kind === "bound" ? `(${q(own.expression)})` : null;
      if (option) out.push(`checked={${leaf}() === ${option}}`, `onChange={() => ${setter}(${option})}`);
      else out.push(`onInput={(e) => ${setter}(e.target.value)}`);
    } else {
      out.push(`value={${leaf}()}`, `onInput={(e) => ${setter}(e.target.value)}`);
    }
  }

  for (const event of node.events) {
    const name = `on${event.name.charAt(0).toUpperCase()}${camel(event.name).slice(1)}`;
    const handler = q(event.handler);
    out.push(`${name}={${/\bevent\b/.test(handler) ? `(event) => ${handler}` : `() => ${handler}`}}`);
  }

  for (const s of node.styles) {
    // Solid's style object takes CSS property names as written in CSS.
    if (s.kind === "declaration") {
      const value = s.literal !== undefined ? jsString(s.literal) : s.unit ? `\`\${${q(s.expression)}}${s.unit}\`` : q(s.expression);
      out.push(`style={{ ${jsString(s.property)}: ${value} }}`);
    }
    if (s.kind === "spread") out.push(`style={${q(s.expression)}}`);
  }
  return out;
}

function print(node, depth, ctx) {
  if (!node) return "";
  const indent = pad(depth);
  const q = (code) => qualify(code, ctx.rewrite, ctx.locals);

  switch (node.kind) {
    case "comment":
      return `${indent}{/*${node.text.replace(/\*\//g, "*\\/")}*/}`;
    case "text": {
      const body = node.parts
        .map((p) => (p.expression !== undefined ? `{${q(p.expression)}}` : p.literal.replace(/\s+/g, " ").replace(/[{}]/g, (c) => `{"${c}"}`)))
        .join("")
        .trim();
      return body ? indent + body : "";
    }
    case "slot":
      return `${indent}{props.children}`;
    case "html":
      return `${indent}<div innerHTML={${q(node.expression)}} />`;
    case "when": {
      const inner = node.children.map((c) => print(c, depth + 1, ctx)).filter(Boolean).join("\n");
      return `${indent}<Show when={${q(node.test)}}>\n${inner}\n${indent}</Show>`;
    }
    case "each": {
      ctx.locals.add(node.item);
      if (node.index) ctx.locals.add(node.index);
      const args = node.index ? `(${node.item}, ${node.index})` : `(${node.item})`;
      const inner = node.children.map((c) => print(c, depth + 1, ctx)).filter(Boolean).join("\n");
      ctx.locals.delete(node.item);
      if (node.index) ctx.locals.delete(node.index);
      return `${indent}<For each={${q(node.list)}}>{${args} => (\n${inner}\n${indent})}</For>`;
    }
    case "fragment": {
      const children = node.children.map((c) => print(c, depth, ctx)).filter(Boolean);
      return children.join("\n");
    }
    case "element": {
      if (!node.tag) {
        const children = node.children.map((c) => print(c, depth, ctx)).filter(Boolean);
        return children.join("\n");
      }
      const props = attributes(node, ctx);
      const open = `<${node.tag}${props.length ? " " + props.join(" ") : ""}`;
      const children = node.children.map((c) => print(c, depth + 1, ctx)).filter(Boolean);
      if (!children.length) return `${indent}${open} />`;
      return [`${indent}${open}>`, ...children, `${indent}</${node.tag}>`].join("\n");
    }
    default:
      return "";
  }
}

export function toSolid(html, { dialect } = {}) {
  const ir = buildIr(html, { dialect });
  const rewrite = new Map();
  for (const m of ir.models) {
    const leaf = m.split(".")[0];
    rewrite.set(leaf, `${leaf.split(".").pop().replace(/[^\w$]/g, "")}()`);
  }
  for (const read of ir.reads) rewrite.set(read, `props.${read}`);
  const ctx = { rewrite, locals: new Set() };
  const body = print(ir.root, 3, ctx);
  return { body, ...ir };
}

export default {
  name: "output-solid",
  version: "0.1.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      if (!ctx.config.solid) return log.debug("not requested");

      let emitted = 0;
      for (const screen of ctx.screens) {
        const Name = pascal(screen.selector) || "Screen";
        const result = screen.template ? toSolid(screen.template) : null;
        const collection = result?.collections[0] ?? "data";
        const props = unique([...screen.inputs, ...(result?.reads ?? []), "loading", "error", "onRetry"]);
        await ctx.write(`src/solid/${Name}.jsx`, COMPONENT({ Name, props, screen, result, collection }));
        emitted += 1;
      }
      log.info(`${emitted} solid component(s)`);
    });
  },
};

const COMPONENT = ({ Name, props, screen, result, collection }) => {
  const models = result?.models ?? [];
  const signals = models
    .map((m) => {
      const leaf = m.split(".").pop().replace(/[^\w$]/g, "");
      return `  const [${leaf}, set${leaf.charAt(0).toUpperCase()}${leaf.slice(1)}] = createSignal("");`;
    })
    .join("\n");
  const uses = ["Show", ...(result?.body.includes("<For") ? ["For"] : [])];
  const qualifiedCollection = collection === "data" ? "props.data" : `props.${collection.split(".")[0]}`;

  return `import { ${[...(models.length ? ["createSignal"] : []), ...uses].join(", ")} } from "solid-js";
import { tokens as T } from "../tokens.js";

/**
 * Ported from ${screen.file} by portamp. Solid target.
 *
 * Props are read as props.x and signals as x() on purpose: destructuring
 * either is how Solid components stop updating. Every state below is present
 * on purpose; delete one only when you have checked the legacy screen
 * genuinely cannot reach it.
 */
export default function ${Name}(props) {
${signals ? signals + "\n" : ""}  return (
    <div style={{ padding: \`\${T.space[3]}px\`, color: T.color.ink, background: T.color.surface }}>
      <Show when={!props.loading} fallback={<div style={{ color: T.color.inkMuted }}>Loading…</div>}>
        <Show
          when={!props.error}
          fallback={
            <div>
              <div style={{ "font-weight": T.weight.bold }}>Could not load</div>
              <div style={{ color: T.color.inkMuted }}>{String(props.error?.message ?? props.error)}</div>
              <button onClick={props.onRetry}>Try again</button>
            </div>
          }
        >
          <Show when={${qualifiedCollection} == null || ${qualifiedCollection}.length !== 0} fallback={<div style={{ color: T.color.inkMuted }}>Nothing to show yet.</div>}>
${result?.body ?? `            {/* No template was found. Port the body from ${screen.file}. */}`}
          </Show>
        </Show>
      </Show>
    </div>
  );
}
`;
};

// plugins/output-lit/index.js
import { buildIr } from "../dsp-ir/ir.js";
import { identifier, jsString, guardHandler } from "../dsp-ir/emit.js";

/**
 * The Lit target: the custom element with a rendering library, for teams that
 * want the platform plus ergonomics. Where output-html hand rolls escaping
 * and delegation because it depends on nothing, this leans on lit-html for
 * both, which is exactly the trade a team picks Lit to make.
 *
 *   lit: true
 */

const pad = (d) => "  ".repeat(d);
const pascal = (sel) => identifier(String(sel).split(/[-_\s]/).filter(Boolean).map((p) => p[0].toUpperCase() + p.slice(1)).join(""), "Screen");

function attributes(node) {
  const out = [];
  const literal = node.classes.filter((c) => c.kind === "literal").map((c) => c.value).join(" ").trim();
  const dynamic = node.classes.filter((c) => c.kind !== "literal");
  if (literal && !dynamic.length) out.push(`class="${literal}"`);
  else if (literal || dynamic.length) {
    const parts = [
      ...(literal ? [jsString(literal)] : []),
      ...dynamic.map((c) => (c.kind === "conditional" ? `(${c.when} ? ${jsString(c.name)} : "")` : `(${c.expression})`)),
    ];
    out.push(`class=\${[${parts.join(", ")}].filter(Boolean).join(" ")}`);
  }
  for (const attr of node.attrs) {
    if (attr.name === "key") continue;
    if (attr.kind === "flag") out.push(attr.name);
    else if (attr.kind === "static") out.push(`${attr.name}="${String(attr.value ?? "").replace(/"/g, "&quot;")}"`);
    else if (attr.kind === "bound") out.push(attr.name === "disabled" ? `?disabled=\${${attr.expression}}` : `${attr.name}=\${${attr.expression}}`);
    else if (attr.kind === "template") out.push(`${attr.name}="${attr.parts.map((p) => (p.expression !== undefined ? `\${${p.expression}}` : p.literal)).join("")}"`);
  }
  if (node.model) {
    const leaf = node.model.split(".").pop().replace(/[^\w$]/g, "");
    if (node.modelKind === "checkbox") {
      out.push(`.checked=\${this.${leaf}}`, `@change=\${(e) => { this.${leaf} = e.target.checked; }}`);
    } else if (node.modelKind === "radio") {
      const own = node.attrs.find((a) => a.name.toLowerCase() === "value");
      const option = own?.kind === "static" ? jsString(own.value) : own?.kind === "bound" ? `(${own.expression})` : null;
      if (option) out.push(`.checked=\${this.${leaf} === ${option}}`, `@change=\${() => { this.${leaf} = ${option}; }}`);
      else out.push(`@change=\${(e) => { this.${leaf} = e.target.value; }}`);
    } else {
      out.push(`.value=\${this.${leaf}}`, `@input=\${(e) => { this.${leaf} = e.target.value; }}`);
    }
  }
  for (const event of node.events) {
    const body = event.handler.startsWith("this.") ? event.handler : `this.${event.handler}`;
    out.push(`@${event.name}=\${(event) => ${guardHandler(event.name, body, event.modifiers)}}`);
  }
  for (const s of node.styles) {
    if (s.kind === "declaration") out.push(`style=\${\`${s.property}: \${${s.literal !== undefined ? jsString(s.literal) : s.expression}}${s.unit ?? ""}\`}`);
  }
  return out;
}

function print(node, depth) {
  if (!node) return "";
  const indent = pad(depth);
  switch (node.kind) {
    case "comment": return `${indent}<!--${node.text}-->`;
    case "text": {
      const body = node.parts.map((p) => (p.expression !== undefined ? `\${${p.expression}}` : p.literal.replace(/\s+/g, " "))).join("").trim();
      return body ? indent + body : "";
    }
    case "slot": {
      const name = node.name ? ` name="${node.name.replace(/"/g, "&quot;")}"` : "";
      const fallback = (node.children ?? []).map((c) => print(c, depth + 1)).filter(Boolean);
      if (!fallback.length) return `${indent}<slot${name}></slot>`;
      return [`${indent}<slot${name}>`, ...fallback, `${indent}</slot>`].join("\n");
    }
    case "html": return `${indent}\${unsafeHTML(${node.expression})}`;
    case "fragment": return node.children.map((c) => print(c, depth)).filter(Boolean).join("\n");
    case "when": {
      const inner = node.children.map((c) => print(c, depth + 1)).filter(Boolean).join("\n");
      return `${indent}\${(${node.test}) ? html\`\n${inner}\n${indent}\` : nothing}`;
    }
    case "each": {
      const inner = node.children.map((c) => print(c, depth + 1)).filter(Boolean).join("\n");
      return `${indent}\${repeat(${node.list} ?? [], (${node.item}) => ${node.key}, (${node.item}${node.index ? `, ${node.index}` : ""}) => html\`\n${inner}\n${indent}\`)}`;
    }
    case "element": {
      if (!node.tag) return node.children.map((c) => print(c, depth)).filter(Boolean).join("\n");
      const props = attributes(node);
      const open = `<${node.tag}${props.length ? " " + props.join(" ") : ""}`;
      const children = node.children.map((c) => print(c, depth + 1)).filter(Boolean);
      if (!children.length) return `${indent}${open}></${node.tag}>`;
      return [`${indent}${open}>`, ...children, `${indent}</${node.tag}>`].join("\n");
    }
    default: return "";
  }
}

export function toLit(html, { dialect } = {}) {
  const ir = buildIr(html, { dialect });
  // A handler expression like `pick(o)` needs `this.` in a class; expressions
  // referring to reads become `this.` too, handled by prefixing the roots.
  const roots = new Set([...ir.reads, ...ir.models.map((m) => m.split(".")[0])]);
  const withThis = (code) => code.replace(/(^|[^.\w$])([A-Za-z_$][\w$]*)/g, (m, before, name) =>
    roots.has(name) ? `${before}this.${name}` : m);
  const rewrite = (node) => {
    if (!node) return node;
    if (node.kind === "text") return { ...node, parts: node.parts.map((p) => (p.expression !== undefined ? { expression: withThis(p.expression) } : p)) };
    if (node.kind === "when") return { ...node, test: withThis(node.test), children: node.children.map(rewrite) };
    if (node.kind === "each") return { ...node, list: withThis(node.list), key: node.key, children: node.children.map(rewrite) };
    if (node.kind === "html") return { ...node, expression: withThis(node.expression) };
    if (node.kind === "element") return {
      ...node,
      attrs: node.attrs.map((a) => (a.kind === "bound" ? { ...a, expression: withThis(a.expression) } : a.kind === "template" ? { ...a, parts: a.parts.map((p) => (p.expression !== undefined ? { expression: withThis(p.expression) } : p)) } : a)),
      classes: node.classes.map((c) => (c.kind === "conditional" ? { ...c, when: withThis(c.when) } : c.kind === "expression" ? { ...c, expression: withThis(c.expression) } : c)),
      styles: node.styles.map((s) => (s.expression ? { ...s, expression: withThis(s.expression) } : s)),
      events: node.events.map((e) => ({ ...e, handler: withThis(e.handler) })),
      children: node.children.map(rewrite),
    };
    if (node.children) return { ...node, children: node.children.map(rewrite) };
    return node;
  };
  const root = rewrite(ir.root);
  return { markup: print(root, 3) || `${pad(3)}<!-- nothing to render -->`, ...ir };
}

export default {
  name: "output-lit",
  version: "0.1.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      if (!ctx.config.lit) return log.debug("not requested");

      let emitted = 0;
      for (const screen of ctx.screens) {
        const name = pascal(screen.selector);
        const tag = screen.selector.includes("-") ? screen.selector : `x-${screen.selector}`;
        const result = screen.template ? toLit(screen.template) : null;
        const collection = result?.collections[0] ?? "data";
        const props = [...new Set([...screen.inputs, ...(result?.reads ?? []), "loading", "error"])];
        await ctx.write(`src/elements/${name}.lit.js`, ELEMENT({ name, tag, props, models: result?.models ?? [], result, collection, screen }));
        emitted += 1;
      }
      log.info(`${emitted} lit element(s)`);
    });
  },
};

const ELEMENT = ({ name, tag, props, models, result, collection, screen }) => {
  const needsRepeat = result?.markup.includes("repeat(");
  const needsUnsafe = result?.markup.includes("unsafeHTML(");
  const empty = collection === "data" ? "!this.data || (Array.isArray(this.data) && this.data.length === 0)" : `!this.${collection} || this.${collection}.length === 0`;
  const fields = [...new Set([...props, ...models.map((m) => m.split(".").pop().replace(/[^\w$]/g, ""))])];

  return `import { LitElement, html, nothing } from "lit";${needsRepeat ? `\nimport { repeat } from "lit/directives/repeat.js";` : ""}${needsUnsafe ? `\nimport { unsafeHTML } from "lit/directives/unsafe-html.js";` : ""}

/**
 * <${tag}>, ported from ${screen.file} by portamp.
 *
 * Every state below is present on purpose. Delete one only when you have
 * checked the legacy screen genuinely cannot reach it.
 */
export class ${name} extends LitElement {
  static properties = {
${fields.map((p) => `    ${p}: {},`).join("\n")}
  };

  render() {
    if (this.loading) return html\`<p class="state state--loading">Loading…</p>\`;
    if (this.error) return html\`
      <div class="state state--error">
        <strong>Could not load</strong>
        <p>\${String(this.error.message ?? this.error)}</p>
        <button type="button" @click=\${() => this.dispatchEvent(new CustomEvent("retry", { bubbles: true, composed: true }))}>Try again</button>
      </div>\`;
    if (${empty}) return html\`<p class="state state--empty">Nothing to show yet.</p>\`;

    return html\`
${result ? result.markup : "      <!-- No template was found for this component. -->"}
    \`;
  }
}

customElements.define(${jsString(tag)}, ${name});
`;
};
