// plugins/output-react/index.js
import { translate } from "./template.js";

const pascal = (sel) =>
  sel.split(/[-_]/).filter(Boolean).map((p) => p[0].toUpperCase() + p.slice(1)).join("");

const unique = (list) => [...new Set(list.filter(Boolean))];

/**
 * Emits one React component per Angular component. The template is translated
 * where there is one to translate, and every state is present either way: an
 * empty state that renders nothing is the single most common thing a port
 * forgets, and it is invisible in review because the screen looks fine when
 * the data happens to be there.
 */
export default {
  name: "output-react",
  version: "0.2.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      let translated = 0;

      for (const s of ctx.screens) {
        const Name = pascal(s.selector) || "Screen";
        const notes = [];
        if (s.usesTwoWay) notes.push(" * Two way binding in the original. Every input here is controlled.");
        if (s.rxjs.length)
          notes.push(` * RxJS in the original: ${s.rxjs.join(", ")}. Mapped to hooks, not ported one for one.`);

        let body = null;
        let models = [];
        let props = unique([...s.inputs, ...s.outputs.map((o) => `on${pascal(o)}`)]);
        let collection = "data";

        if (s.template) {
          const result = translate(s.template, { indent: 3 });
          body = result.jsx;
          models = result.models;
          collection = result.collections[0] ?? "data";
          props = unique([...props, ...result.reads]);
          translated += 1;
          notes.push(` * Template translated from ${s.templateOrigin ?? "the decorator"}.`);
          for (const note of result.notes) ctx.unverified(`<${s.selector}>: ${note}`);
        } else {
          notes.push(" * No template was found, so the body below is a placeholder.");
        }

        props = unique([...props, "loading", "error", "onRetry"]);
        const usesChildren = Boolean(body && body.includes("{children}"));
        if (usesChildren) props.push("children");

        await ctx.write(
          `src/features/${Name}/${Name}.jsx`,
          COMPONENT({ Name, props, notes, origin: s.file, body, models, collection })
        );
      }

      log.info(
        `${ctx.screens.length} component(s) emitted` +
          (ctx.screens.length ? `, ${translated} template(s) translated` : "")
      );
    });
  },
};

const PLACEHOLDER = (origin) =>
  `      {/* No template was found for this component. Port the body from ${origin}. */}`;

const COMPONENT = ({ Name, props, notes, origin, body, models, collection }) => {
  const state = models
    .map((m) => {
      const leaf = m.split(".").pop().replace(/[^\w$]/g, "");
      return `  const [${leaf}, set${leaf.charAt(0).toUpperCase()}${leaf.slice(1)}] = useState("");`;
    })
    .join("\n");

  const empty =
    collection === "data"
      ? "!data || (Array.isArray(data) && data.length === 0)"
      : `!${collection} || ${collection}.length === 0`;

  return `import React${models.length ? ", { useState }" : ""} from "react";
import { tokens as T } from "../../tokens.js";

/**
 * Ported from ${origin}
${notes.length ? notes.join("\n") : " *"}
 *
 * Every state below is present on purpose. Delete one only when you have
 * checked the legacy screen genuinely cannot reach it.
 */
export default function ${Name}({ ${props.join(", ")} }) {
${state ? state + "\n" : ""}  if (loading) return <div style={{ padding: T.space[4], color: T.color.inkMuted }}>Loading…</div>;

  if (error)
    return (
      <div style={{ padding: T.space[4] }}>
        <div style={{ fontWeight: T.weight.bold, marginBottom: T.space[0] }}>Could not load</div>
        <div style={{ color: T.color.inkMuted, fontSize: T.size.sm }}>{String(error.message ?? error)}</div>
        <button onClick={onRetry} style={{ marginTop: T.space[2] }}>Try again</button>
      </div>
    );

  if (${empty})
    return (
      <div style={{ padding: T.space[5], textAlign: "center", color: T.color.inkMuted }}>
        Nothing to show yet.
      </div>
    );

  return (
    <div style={{ padding: T.space[3], color: T.color.ink, background: T.color.surface }}>
${body ?? PLACEHOLDER(origin)}
    </div>
  );
}
`;
};

// plugins/output-qwik/index.js
import { translate } from "../output-react/template.js";
import { pascal, unique } from "../dsp-ir/emit.js";

/**
 * The Qwik target. The body is the same JSX the React printer proves against
 * the other targets, because Qwik renders JSX; what Qwik changes is two things
 * this printer has to respect or the output does not run. Every handler prop
 * carries the `$` the optimizer needs to split it out, and local state is a
 * signal read through `.value` rather than a hook returning a pair. Both are
 * mechanical rewrites over the proven JSX, so nothing upstream learned Qwik.
 *
 *   qwik: true
 */

/** React handler props become Qwik's `$` suffixed props: onClick -> onClick$. */
const suffixHandlers = (jsx) => jsx.replace(/\bon([A-Z][A-Za-z]+)=\{/g, "on$1$$={");

/** A model read `{leaf}` or `={leaf}` becomes the signal read `{leaf.value}`. */
function readThroughValue(jsx, leaves) {
  let out = jsx;
  for (const leaf of leaves) {
    out = out.replace(new RegExp(`([={])(${leaf})\\}`, "g"), "$1$2.value}");
  }
  return out;
}

const leafOf = (model) => model.split(".").pop().replace(/[^\w$]/g, "");

export default {
  name: "output-qwik",
  version: "0.1.0",
  class: "output",
  setup({ on, log }) {
    on("emit", async (ctx) => {
      if (!ctx.config.qwik) return log.debug("not requested");

      const components = new Map(ctx.screens.map((s) => [s.selector.toLowerCase(), { name: pascal(s.selector) || "Screen" }]));
      let emitted = 0;
      for (const screen of ctx.screens) {
        const Name = pascal(screen.selector) || "Screen";
        const scoped = new Map(components);
        scoped.delete(screen.selector.toLowerCase());
        const result = screen.template ? translate(screen.template, { indent: 3, components: scoped }) : null;

        const models = result?.models ?? [];
        const leaves = unique(models.map(leafOf));
        let body = result?.jsx ?? null;
        if (body) body = readThroughValue(suffixHandlers(body), leaves);

        const collection = result?.collections[0] ?? "data";
        const props = unique([
          ...screen.inputs,
          ...screen.outputs.map((o) => `on${pascal(o)}`),
          ...(result?.reads ?? []),
          "loading", "error", "onRetry",
        ]);
        const referenced = (result?.components ?? []).map((sel) => components.get(sel).name);

        await ctx.write(`src/qwik/${Name}/${Name}.jsx`, COMPONENT({ Name, props, leaves, body, collection, screen, referenced: unique(referenced) }));
        emitted += 1;
      }
      log.info(`${emitted} qwik component(s)`);
    });
  },
};

const COMPONENT = ({ Name, props, leaves, body, collection, screen, referenced }) => {
  // A signal per model, and a plain local setter the handlers call. The setter
  // is captured by the component closure, so it needs no $ of its own.
  const signals = leaves
    .map((leaf) => `  const ${leaf} = useSignal("");\n  const set${leaf.charAt(0).toUpperCase()}${leaf.slice(1)} = (v) => { ${leaf}.value = v; };`)
    .join("\n");

  const empty = collection === "data"
    ? "!data || (Array.isArray(data) && data.length === 0)"
    : `!${collection} || ${collection}.length === 0`;
  const imports = referenced.map((name) => `import { ${name} } from "../${name}/${name}.jsx";`).join("\n");

  return `import { component$, useSignal } from "@builder.io/qwik";
import { tokens as T } from "../../tokens.js";
${imports ? imports + "\n" : ""}
/**
 * Ported from ${screen.file} by portamp. Qwik target: the proven JSX, handlers
 * split with $, and local state as signals read through .value.
 *
 * Every state below is present on purpose. Delete one only when you have
 * checked the legacy screen genuinely cannot reach it.
 */
export const ${Name} = component$((props) => {
  const { ${props.join(", ")} } = props;
${signals ? signals + "\n" : ""}
  if (loading) return <div role="status" style={{ padding: T.space[4], color: T.color.inkMuted }}>Loading…</div>;

  if (error)
    return (
      <div role="alert" style={{ padding: T.space[4] }}>
        <div style={{ fontWeight: T.weight.bold }}>Could not load</div>
        <div style={{ color: T.color.inkMuted, fontSize: T.size.sm }}>{String(error.message ?? error)}</div>
        <button onClick$={onRetry} style={{ marginTop: T.space[2] }}>Try again</button>
      </div>
    );

  if (${empty})
    return (
      <div style={{ padding: T.space[5], textAlign: "center", color: T.color.inkMuted }}>
        Nothing to show yet.
      </div>
    );

  return (
    <div style={{ padding: T.space[3], color: T.color.ink, background: T.color.surface }}>
${body ?? `      {/* No template was found. Port the body from ${screen.file}. */}`}
    </div>
  );
});
`;
};
