// plugins/input-react/index.js
import { readFile } from "node:fs/promises";
import { basename, extname } from "node:path";
import { pascal } from "../dsp-ir/emit.js";

/**
 * portamp reads what it writes.
 *
 * Every other reader lowers a legacy dialect onto the IR. This one reads
 * React, the language portamp most often emits, and lowers its JSX onto the
 * same AngularJS attribute dialect the rest of the tool already reads. That
 * closes the loop two ways: a React front end becomes a source portamp can
 * port to Vue or Svelte, and the emitted React can be read back and checked
 * against what it came from, which is what vis-roundtrip does.
 *
 * JSX has no general inverse, so this handles the shapes portamp emits and the
 * common hand written ones: `{cond && (<x/>)}` is a conditional, `{list.map(
 * (item) => <x/>)}` is a loop, `{expr}` in text is interpolation, an input
 * with value and onChange is a model, and an event prop is an event. A ternary
 * or anything it cannot place is left as written and named, never guessed.
 */

/** The matching `}` for the `{` at `open`, respecting strings and nesting. */
function matchBrace(text, open) {
  let depth = 0;
  let quote = null;
  for (let i = open; i < text.length; i += 1) {
    const c = text[i];
    if (quote) { if (c === quote && text[i - 1] !== "\\") quote = null; continue; }
    if (c === "'" || c === '"' || c === "`") quote = c;
    else if (c === "{") depth += 1;
    else if (c === "}") { depth -= 1; if (depth === 0) return i; }
  }
  return -1;
}

/** Insert an attribute into the first opening tag of a JSX fragment. */
function injectAttr(jsx, attr) {
  return jsx.replace(/<([a-zA-Z][\w.-]*)/, (m, tag) => `<${tag} ${attr}`);
}

/** Strip a `key={...}` attribute, which the dialect does not carry. */
const dropKey = (jsx) => jsx.replace(/\s+key=\{[^}]*\}/, "");

/** A React event prop name to the dialect event, or null if it has none. */
const EVENT = { onClick: "click", onChange: "change", onInput: "change", onSubmit: "submit",
  onBlur: "blur", onFocus: "focus", onKeyUp: "keyup", onKeyDown: "keydown",
  onMouseOver: "mouseover", onMouseOut: "mouseout", onDoubleClick: "dblclick" };

/** The call inside a handler expression: `(event) => foo(x)` -> `foo(x)`. */
function handlerCall(expr) {
  const arrow = /^\s*\(?[\w\s,]*\)?\s*=>\s*([\s\S]+?)\s*$/.exec(expr);
  let body = (arrow ? arrow[1] : expr).trim().replace(/^\{|\}$/g, "").trim().replace(/;$/, "");
  if (/^[\w.$]+$/.test(body)) body = `${body}()`;
  return body;
}

/**
 * Lower a JSX fragment onto the dialect. Recursive, so a loop inside a
 * conditional inside a loop all come across. `note` records what could not be
 * reversed rather than guessing at it.
 */
export function lowerReact(jsx, note = () => {}) {
  let out = "";
  let i = 0;
  while (i < jsx.length) {
    const c = jsx[i];
    if (c !== "{") { out += c; i += 1; continue; }
    // `{{` is a style-like object; skip the whole double-braced value.
    const end = matchBrace(jsx, i);
    if (end === -1) { out += c; i += 1; continue; }
    const inner = jsx.slice(i + 1, end).trim();

    const loop = /^([\w.$]+)\s*\.\s*map\s*\(\s*\(?\s*([\w$]+)\s*(?:,\s*[\w$]+\s*)?\)?\s*=>\s*([\s\S]*)$/.exec(inner);
    const cond = /^([^&]+?)\s*&&\s*([\s\S]*)$/.exec(inner);

    if (loop && /<[a-zA-Z]/.test(loop[3])) {
      // The arrow body wraps the JSX in one paren and .map() adds its own, so
      // strip every trailing paren, not just one. key is dropped before the
      // recursion so its expression is never read as interpolation.
      const body = dropKey(loop[3].replace(/^\(\s*/, "").replace(/[\s)]+$/, "").trim());
      out += injectAttr(lowerReact(body, note), `ng-repeat="${loop[2]} in ${loop[1]}"`);
    } else if (cond && /<[a-zA-Z]/.test(cond[2])) {
      const body = cond[2].replace(/^\(\s*/, "").replace(/[\s)]+$/, "").trim();
      out += injectAttr(lowerReact(body, note), `ng-if="${cond[1].trim()}"`);
    } else if (/\?/.test(inner) && /:/.test(inner) && /<[a-zA-Z]/.test(inner)) {
      note("A JSX ternary was left as written; a conditional with two branches is a person's call to split.");
      out += `{{ ${inner} }}`;
    } else if (/<[a-zA-Z]/.test(inner)) {
      // A brace holding markup this pass could not classify: recurse so its
      // own children still lower, rather than dropping them.
      out += lowerReact(inner, note);
    } else {
      out += `{{ ${inner} }}`;
    }
    i = end + 1;
  }
  return out;
}

/** Lower a component's whole return body: attributes first, then structure. */
export function lowerBody(jsx, note = () => {}) {
  let text = jsx
    // A style object never survives structural comparison and its inner braces
    // confuse the pass; drop it and say so once.
    .replace(/\s+style=\{\{[\s\S]*?\}\}/g, () => { note("A style prop was dropped; the dialect carries structure, not inline style."); return ""; })
    .replace(/\bclassName=/g, "class=");

  // An input that binds value and onChange is a two way model.
  text = text.replace(/<input\b([^>]*)>/g, (m, attrs) => {
    const value = /\bvalue=\{([\w.$]+)\}/.exec(attrs);
    if (value && /\bonChange=/.test(attrs)) {
      const rest = attrs.replace(/\bvalue=\{[\w.$]+\}/, "").replace(/\bonChange=\{[^}]*\}/, "").trim();
      return `<input ng-model="${value[1]}"${rest ? " " + rest : ""}>`;
    }
    return m;
  });

  // Event props become dialect events.
  text = text.replace(/\son([A-Z]\w+)=\{([\s\S]*?)\}(?=\s|\/?>)/g, (m, name, expr) => {
    const event = EVENT[`on${name}`];
    if (!event) { note(`The \`on${name}\` handler has no dialect event; it was dropped.`); return ""; }
    return ` ng-${event}="${handlerCall(expr).replace(/"/g, "'")}"`;
  });

  return lowerReact(text, note);
}

export function readComponent(source, rel, note = () => {}) {
  const screens = [];
  // function Name(...) { ... } or const Name = (...) => ...
  const decl = /(?:export\s+default\s+)?function\s+([A-Z]\w*)\s*\(([^)]*)\)|(?:export\s+default\s+)?const\s+([A-Z]\w*)\s*=\s*\(([^)]*)\)\s*=>/g;
  let m;
  while ((m = decl.exec(source))) {
    const name = m[1] ?? m[3];
    const params = m[2] ?? m[4] ?? "";
    const destructured = /\{([^}]*)\}/.exec(params)?.[1] ?? "";
    const inputs = destructured.split(",").map((s) => s.trim().split(/[:=]/)[0].trim()).filter((n) => /^[\w$]+$/.test(n) && !["loading", "error", "onRetry", "children"].includes(n));

    // The component body is from the declaration to the balanced end; the
    // return's JSX is what we lower.
    const bodyStart = source.indexOf("{", m.index + m[0].length - 1);
    const ret = /return\s*\(([\s\S]*?)\);\s*\n?\s*\}?/.exec(source.slice(bodyStart)) ?? /return\s*(<[\s\S]*?>[\s\S]*?);/.exec(source.slice(bodyStart));
    const jsx = ret ? ret[1].trim() : null;
    const template = jsx ? lowerBody(jsx, note) : null;

    const outputs = inputs.filter((n) => /^on[A-Z]/.test(n)).map((n) => n.replace(/^on/, "").replace(/^./, (c) => c.toLowerCase()));
    screens.push({
      selector: name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase(),
      className: name,
      file: rel,
      inputs: inputs.filter((n) => !/^on[A-Z]/.test(n)),
      outputs,
      template,
      templateOrigin: template ? "a React component, lowered" : null,
      usesNgIf: /ng-if/.test(template ?? ""),
      usesNgFor: /ng-repeat/.test(template ?? ""),
      usesTwoWay: /ng-model/.test(template ?? ""),
      rxjs: [],
      readBy: "react",
    });
  }
  return screens;
}

export default {
  name: "input-react",
  version: "0.1.0",
  class: "input",
  setup({ on, log }) {
    on("extract", async (ctx) => {
      const files = ctx.sources.files.filter((f) => /\.(jsx|tsx)$/i.test(f.rel) && !/\.(test|spec|stories)\./i.test(f.rel));
      let count = 0;
      const notes = [];
      const note = (t) => { if (!notes.includes(t)) notes.push(t); };
      for (const file of files) {
        const text = await readFile(file.path, "utf8").catch(() => "");
        if (!/\breturn\s*[(<]/.test(text) || !/<[A-Za-z]/.test(text)) continue;
        for (const screen of readComponent(text, file.rel, note)) {
          ctx.screens.push(screen);
          count += 1;
        }
      }
      if (!count) return log.debug("no React components");
      for (const n of notes) ctx.unverified(n);
      log.info(`${count} React component(s), lowered onto the dialect`);
    });
  },
};

// plugins/input-webcomponents/index.js
import { readFile } from "node:fs/promises";
import { pascal } from "../dsp-ir/emit.js";

/**
 * Reads vanilla custom elements onto the same dialect every other reader targets.
 *
 * Before Lit, Stencil, Polymer or Riot, a team could reach for the platform
 * itself: `class X extends HTMLElement`, a `static get observedAttributes` that
 * lists the attributes it reacts to, a `connectedCallback` that writes its
 * markup with `innerHTML`, and `dispatchEvent(new CustomEvent('name'))` to speak
 * back out. `customElements.define('x-thing', X)` gives it a tag. This reads
 * that shape:
 *
 *   - the registered tag is the component's name, so it reaches the translator
 *     and every emitter as any other component.
 *   - observedAttributes are its inputs.
 *   - the CustomEvent names it dispatches are its outputs.
 *   - the innerHTML template literal is its markup; a `${x}` interpolation
 *     lowers to `{{ x }}` once `this.` is stripped, the way every other reader's
 *     expressions look.
 *
 * A vanilla element often builds its DOM imperatively, and an expression with no
 * plain interpolation (a `.map`, a ternary, a nested template) has no honest
 * lowering, so it is named through the note rather than guessed. No dependency.
 */

/** The balanced `{...}` body of `class <name> extends HTMLElement`, or null. */
function classBody(source, name) {
  const open = new RegExp(`class\\s+${name}\\s+extends\\s+HTMLElement\\s*\\{`).exec(source);
  if (!open) return null;
  let depth = 1;
  let i = open.index + open[0].length;
  const start = i;
  for (; i < source.length; i += 1) {
    if (source[i] === "{") depth += 1;
    else if (source[i] === "}") { depth -= 1; if (depth === 0) return source.slice(start, i); }
  }
  return null;
}

/** Tag -> class name for every customElements.define in the file. */
export function readDefines(source) {
  const map = [];
  for (const m of source.matchAll(/customElements\s*\.\s*define\s*\(\s*(['"`])([\w-]+)\1\s*,\s*([A-Za-z_$][\w$]*)/g)) {
    map.push({ tag: m[2], cls: m[3] });
  }
  return map;
}

/** The string entries of `static get observedAttributes() { return [...] }`. */
export function readObserved(body) {
  const m = /observedAttributes\s*\(\s*\)\s*\{[\s\S]*?return\s*\[([^\]]*)\]/.exec(body);
  if (!m) return [];
  return [...m[1].matchAll(/(['"`])([\w-]+)\1/g)].map((x) => x[2]);
}

/** The CustomEvent names dispatched from the body. */
export function readEvents(body) {
  const out = [];
  for (const m of body.matchAll(/new\s+CustomEvent\s*\(\s*(['"`])([\w-]+)\1/g)) if (!out.includes(m[2])) out.push(m[2]);
  return out;
}

/** The first innerHTML template literal assigned in the body, or null. */
export function readTemplateLiteral(body) {
  const m = /\.innerHTML\s*=\s*`/.exec(body);
  if (!m) return null;
  const start = m.index + m[0].length;
  for (let i = start; i < body.length; i += 1) {
    if (body[i] === "\\") { i += 1; continue; }
    if (body[i] === "`") return body.slice(start, i);
  }
  return null;
}

/** Lower a template literal's `${...}` to interpolation; note what cannot be. */
export function lowerTemplate(tpl, note = () => {}) {
  let out = "";
  for (let i = 0; i < tpl.length; i += 1) {
    if (tpl[i] === "$" && tpl[i + 1] === "{") {
      let depth = 1;
      let j = i + 2;
      for (; j < tpl.length && depth > 0; j += 1) {
        if (tpl[j] === "{") depth += 1;
        else if (tpl[j] === "}") depth -= 1;
      }
      const expr = tpl.slice(i + 2, j - 1).trim();
      const plain = expr.replace(/\bthis\./g, "");
      if (/`|\.map\s*\(|\?[^?]*:/.test(plain)) {
        note(`a template expression in a custom element (${plain.slice(0, 40)}...) has no plain interpolation and was left out; port it by hand.`);
      } else {
        out += `{{ ${plain} }}`;
      }
      i = j - 1;
    } else {
      out += tpl[i];
    }
  }
  return out.trim();
}

export function readComponent(source, cls, tag, rel, note = () => {}) {
  const body = classBody(source, cls);
  if (body == null) return null;
  const inputs = readObserved(body);
  const outputs = readEvents(body);
  const raw = readTemplateLiteral(body);
  const template = raw != null ? lowerTemplate(raw, note) : null;
  return {
    selector: tag,
    className: pascal(tag),
    file: rel,
    inputs,
    outputs,
    template,
    templateOrigin: template ? "a vanilla custom element, lowered" : null,
    usesNgIf: false,
    usesNgFor: false,
    usesTwoWay: false,
    rxjs: [],
    readBy: "webcomponents",
  };
}

function looksLikeWebComponent(source) {
  return /extends\s+HTMLElement\b/.test(source) && /customElements\s*\.\s*define\s*\(/.test(source);
}

export default {
  name: "input-webcomponents",
  version: "0.1.0",
  class: "input",
  setup({ on, log }) {
    on("extract", async (ctx) => {
      const files = ctx.sources.files.filter((f) => /\.(js|mjs|ts)$/i.test(f.rel) && !/\.min\./.test(f.rel));
      if (!files.length) return log.debug("no scripts to read for custom elements");
      let count = 0;
      const notes = [];
      const note = (t) => { if (!notes.includes(t)) notes.push(t); };
      for (const file of files) {
        const text = await readFile(file.path, "utf8").catch(() => "");
        if (!text || !looksLikeWebComponent(text)) continue;
        for (const { tag, cls } of readDefines(text)) {
          const screen = readComponent(text, cls, tag, file.rel, note);
          if (!screen) continue;
          if (!screen.template) { ctx.unverified(`<${tag}> is a custom element but builds its DOM without an innerHTML template, so only its inputs and outputs are read.`); continue; }
          for (const m of text.matchAll(/\bfetch\(\s*(['"`])([^'"`]+)\1/g)) ctx.api.calls.push({ method: "GET", path: m[2], file: file.rel, headers: null, body: null });
          ctx.screens.push(screen);
          count += 1;
        }
      }
      if (!count) return log.debug("no custom elements read");
      for (const n of notes) ctx.unverified(n);
      log.info(`${count} custom element(s) lowered`);
    });
  },
};
